version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: summarizer
      POSTGRES_PASSWORD: empty
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
