[tool.poetry]
name = "summ"
version = "0.1.0"
description = ""
authors = ["Alex <aleks@fellow.co>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
django = "^5.0"
django-rq = "^2.9.0"
pytube = "^15.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
