# Generated by Django 5.0.7 on 2024-07-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_youtubevideo_chapters_and_more'),
        ('telegram', '0003_singlevideotosend'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='+', to='main.youtubechannel'),
        ),
    ]
