# Generated by Django 5.0.2 on 2024-03-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_youtubevideo_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='transcription_segments',
            field=models.JSONField(default=list),
        ),
    ]
