# Generated by Django 5.0.6 on 2024-07-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_youtubevideo_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='chapters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='transcription_segments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
