# Generated by Django 5.0.6 on 2024-07-03 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_alter_youtubevideo_chapters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_id', models.CharField(db_index=True, max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.youtubevideo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
